### ISSUE TITLE
Fact "lsbdistdesc" causes error on Windows and FreeBSD

### ISSUE THREAD

**Issue by fraenki** [markt-de/puppet-marktlib#1]
```
Error while resolving custom fact fact='lsbdistdesc', resolution='<anonymous>': undefined method `[]' for nil:NilClass
```

This fact work should be restricted to Linux operating systems.

**Comment by Lightning-** [comment]
true that; thx for noticing!

fixed with c9974c8 and released as [v0.1.1](https://github.com/markt-de/puppet-marktlib/releases/tag/v0.1.1)
